package com.izzydrive.backend.model;

public enum NotificationStatus {
    NEW_RESERVATION,
    REJECTED_RESERVATION,
    NEW_DRIVING,
    REJECTED_DRIVING_PASSENGER,
    REJECTED_DRIVING_DRIVER,
    REPORT_DRIVER,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    PAYMENT_EXPIRED,
    NEW_DRIVING_DRIVER,
    RESERVATION_REMINDER,
    PAYMENT_RESERVATION,
    RESERVATION_DELETE,
    DRIVER_CHANGE_DATA,
    CAR_CHANGE_DATA,
    ADMIN_RESPONSE
}
