export enum NotificationStatus {
  NEW_RESERVATION = "NEW_RESERVATION",
  REJECTED_RESERVATION = "REJECTED_RESERVATION",
  NEW_DRIVING = "NEW_DRIVING",
  REJECTED_DRIVING_PASSENGER = "REJECTED_DRIVING_PASSENGER",
  REJECTED_DRIVING_DRIVER = "REJECTED_DRIVING_DRIVER",
  REPORT_DRIVER = "REPORT_DRIVER",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILURE = "PAYMENT_FAILURE",
  PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
  NEW_DRIVING_DRIVER = "NEW_DRIVING_DRIVER",
  RESERVATION_REMINDER = "RESERVATION_REMINDER",
  PAYMENT_RESERVATION = "PAYMENT_RESERVATION",
  RESERVATION_DELETE = "RESERVATION_DELETE",
  DRIVER_ARRIVED_AT_START = "DRIVER_ARRIVED_AT_START",
  REGULAR_DRIVING_CANCELED_TO_PASSENGER = "REGULAR_DRIVING_CANCELED_TO_PASSENGER"
}
