export enum NotificationStatus {
  NEW_RESERVATION = "NEW_RESERVATION",
  REJECTED_RESERVATION = "REJECTED_RESERVATION",
  NEW_DRIVING = "NEW_DRIVING",
  REJECTED_DRIVING_PASSENGER = "REJECTED_DRIVING_PASSENGER",
  REJECTED_DRIVING_DRIVER = "REJECTED_DRIVING_DRIVER",
  REPORT_DRIVER = "REPORT_DRIVER",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILURE = "PAYMENT_FAILURE",
  PAYMENT_EXPIRED = "PAYMENT_EXPIRED",
  NEW_DRIVING_DRIVER = "NEW_DRIVING_DRIVER"
  //obavestenja o rezervaciji na 15, 10, 5 min
}
