spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 83743871907-93ba97v7t6j53p316sl6js0pgj9hmp51.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - public_profile